import { CSSProperties } from "react";
import { theme } from "./theme";

export const styles: Record<string, CSSProperties> = {
    customCard: {
        padding: "1.1rem",
    },
    controlsRow: {
        display: "flex",
        alignItems: "center",
        gap: "0.8rem",
        flexWrap: "wrap",
        marginBottom: "0.9rem",
    },
    separator: {
        color: theme.fgMuted,
        fontWeight: 700,
    },
    contentLayout: {
        display: "flex",
        gap: "0.9rem",
        alignItems: "stretch",
        flexWrap: "wrap",
        marginBottom: "0.9rem",
    },
    leftLayout: {
        flex: "1 1 760px",
        minWidth: "620px",
    },
    rightLayout: {
        flex: "0 0 380px",
        width: "380px",
        minWidth: "360px",
    },
    selectionGrid: {
        display: "grid",
        gridTemplateColumns: "minmax(280px, 1fr) minmax(340px, 1.2fr)",
        gap: "0.9rem",
    },
    selectionPanel: {
        border: `1px solid ${theme.borderStrong}`,
        borderRadius: "14px",
        background: "#f7fbff",
        minHeight: "520px",
        padding: "0.62rem",
        display: "flex",
        flexDirection: "column",
        boxShadow: "0 6px 14px rgba(20, 72, 141, 0.08)",
    },
    duplicatePanel: {
        border: `1px solid ${theme.borderStrong}`,
        borderRadius: "14px",
        background: "#f7fbff",
        minHeight: "520px",
        padding: "0.62rem",
        display: "flex",
        flexDirection: "column",
        boxShadow: "0 6px 14px rgba(20, 72, 141, 0.08)",
    },
    panelHeader: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: "0.5rem",
        marginBottom: "0.48rem",
    },
    panelTitle: {
        color: theme.fgStrong,
        fontWeight: 800,
        fontSize: "0.92rem",
        lineHeight: 1.2,
    },
    panelSubTitle: {
        color: theme.fgMuted,
        fontSize: "0.78rem",
        marginTop: "0.12rem",
    },
    panelTools: {
        display: "flex",
        gap: "0.4rem",
    },
    summaryChip: {
        border: `1px solid ${theme.borderStrong}`,
        borderRadius: "999px",
        background: "#fff",
        color: theme.brandDeep,
        padding: "0.18rem 0.56rem",
        fontSize: "0.76rem",
        fontWeight: 800,
        whiteSpace: "nowrap",
    },
    toolBtn: {
        border: `1px solid ${theme.borderStrong}`,
        borderRadius: "9px",
        padding: "0.28rem 0.55rem",
        fontSize: "0.77rem",
        fontWeight: 700,
        background: "#fff",
        color: theme.brandDeep,
        cursor: "pointer",
    },
    checkListBox: {
        border: `1px solid ${theme.borderStrong}`,
        borderRadius: "11px",
        background: "#fff",
        flex: 1,
        overflowY: "auto",
        padding: "0.35rem",
    },
    checkRow: {
        display: "flex",
        alignItems: "flex-start",
        gap: "0.52rem",
        padding: "0.42rem 0.46rem",
        borderRadius: "9px",
        cursor: "pointer",
        border: "1px solid transparent",
    },
    checkRowActive: {
        display: "flex",
        alignItems: "flex-start",
        gap: "0.52rem",
        padding: "0.42rem 0.46rem",
        borderRadius: "9px",
        cursor: "pointer",
        border: `1px solid ${theme.borderStrong}`,
        background: "rgba(46, 123, 219, 0.14)",
    },
    checkInput: {
        marginTop: "0.08rem",
        accentColor: "var(--brand-500)",
    },
    checkText: {
        color: theme.fgStrong,
        fontSize: "0.83rem",
        wordBreak: "break-all",
        lineHeight: "1.3",
    },
    duplicateBadge: {
        marginLeft: "auto",
        fontSize: "0.71rem",
        fontWeight: 800,
        color: "#1f5eb4",
        background: "rgba(31, 94, 180, 0.12)",
        borderRadius: "999px",
        padding: "0.11rem 0.42rem",
        whiteSpace: "nowrap",
    },
    emptyText: {
        color: theme.fgMuted,
        fontSize: "0.83rem",
        padding: "0.5rem",
    },
    duplicateToolbar: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.42rem",
        alignItems: "center",
        marginBottom: "0.44rem",
    },
    duplicateFilterCheck: {
        display: "inline-flex",
        alignItems: "center",
        gap: "0.32rem",
        color: theme.fgStrong,
        fontSize: "0.8rem",
        fontWeight: 700,
        whiteSpace: "nowrap",
    },
    duplicateSearchInput: {
        border: `1px solid ${theme.borderStrong}`,
        borderRadius: "10px",
        background: "#fff",
        color: theme.fgStrong,
        fontSize: "0.8rem",
        padding: "0.34rem 0.54rem",
        outline: "none",
        minWidth: "180px",
        flex: "1 1 220px",
    },
    duplicateBulkSelect: {
        borderRadius: "10px",
        border: `1px solid ${theme.borderStrong}`,
        background: "#fff",
        color: theme.fgStrong,
        fontSize: "0.8rem",
        padding: "0.34rem 0.52rem",
        minWidth: "180px",
        flex: "1 1 220px",
    },
    duplicateMetaText: {
        color: theme.fgMuted,
        fontSize: "0.79rem",
        marginBottom: "0.34rem",
        paddingLeft: "0.05rem",
    },
    duplicateUnresolved: {
        color: "#b85050",
        fontWeight: 700,
    },
    duplicateListBox: {
        display: "flex",
        flexDirection: "column",
        gap: "0.42rem",
        maxHeight: "420px",
        overflowY: "auto",
        border: `1px solid ${theme.borderStrong}`,
        borderRadius: "11px",
        background: "#fff",
        padding: "0.42rem",
        flex: 1,
    },
    duplicateRow: {
        display: "grid",
        gridTemplateColumns: "1fr minmax(160px, 44%)",
        gap: "0.5rem",
        alignItems: "start",
    },
    duplicatePathWrap: {
        display: "flex",
        alignItems: "flex-start",
        gap: "0.34rem",
        minWidth: 0,
    },
    duplicateIndex: {
        flexShrink: 0,
        minWidth: "1.6rem",
        height: "1.28rem",
        borderRadius: "999px",
        background: "rgba(46, 123, 219, 0.12)",
        color: theme.brandDeep,
        fontWeight: 800,
        fontSize: "0.72rem",
        lineHeight: "1.28rem",
        textAlign: "center",
    },
    duplicatePath: {
        color: theme.fgStrong,
        fontSize: "0.81rem",
        wordBreak: "break-all",
        lineHeight: "1.24",
        minWidth: 0,
    },
    duplicateSelect: {
        borderRadius: "10px",
        border: `1px solid ${theme.borderStrong}`,
        background: "#fbfdff",
        color: theme.fgStrong,
        fontSize: "0.79rem",
        padding: "0.32rem 0.5rem",
        minWidth: "145px",
    },
    versionTypeText: {
        marginBottom: "0.85rem",
        color: theme.fgMuted,
        fontSize: "0.84rem",
    },
    dateInput: {
        padding: "0.62rem 0.78rem",
        borderRadius: "10px",
        border: `1px solid ${theme.borderStrong}`,
        background: "#fbfdff",
        color: theme.fgStrong,
        minWidth: "128px",
        outline: "none",
        fontSize: "0.84rem",
    },
    extractBtn: {
        width: "100%",
        background: `linear-gradient(135deg, ${theme.brandDeep} 0%, ${theme.brand} 100%)`,
        color: "#fff",
        padding: "0.74rem",
        border: "none",
        borderRadius: "12px",
        fontWeight: 800,
        letterSpacing: "0.01em",
        boxShadow: "0 10px 22px rgba(23, 82, 160, 0.24)",
        cursor: "pointer",
    },
};
