package com.deployProject.cli

import java.nio.file.Paths

class DeployCliScript {

    /**
     * Keep the banner ASCII-only so it renders the same on Linux shells
     * regardless of locale settings.
     */
    private val asciiBanner = """
        ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗    ███╗   ███╗ █████╗ ███╗   ██╗
        ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝    ████╗ ████║██╔══██╗████╗  ██║
        ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝     ██╔████╔██║███████║██╔██╗ ██║
        ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝      ██║╚██╔╝██║██╔══██║██║╚██╗██║
        ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║       ██║ ╚═╝ ██║██║  ██║██║ ╚████║
        ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝       ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝
        """.trimIndent()

    fun createDeployScript(
        changedFiles: List<String>,
        deployDir: String
    ): List<Pair<String, List<String>>> {
        val rawRoot = Paths.get(deployDir).toAbsolutePath().normalize().toString()
        val root = rawRoot.replace('\\', '/').replaceFirst(Regex("^[A-Za-z]:"), "")
        val backupStampExpr = "\$(date +'%Y%m%d_%H%M%S')"

        val stagingRelPaths = changedFiles
            .map(::normalizeRelativePath)
            .distinct()

        // Staging paths come from the extracted bundle. Deploy paths are based on
        // the exploded WAR layout. At runtime the script can still fall back to the
        // source-tree path when the server keeps the project structure under ROOT.
        val pathMappings = stagingRelPaths
            .map { stagingPath -> stagingPath to mapToDeployRelativePath(stagingPath) }
            .distinct()

        val scriptLines = mutableListOf<String>().apply {
            add("#!/usr/bin/env bash")
            add("set -euo pipefail")
            add("")
            add("ROOT=\"$root\"")
            add("SCRIPT_DIR=\"\$(cd \"\$(dirname \"\${BASH_SOURCE[0]}\")\" && pwd)\"")
            add("STAGING_DIR=\"\$SCRIPT_DIR\"")
            add("")
            add("cat << 'BANNER'")
            asciiBanner.lines().forEach { add(it) }
            add("BANNER")
            add("")
            add("[ -d \"\$ROOT\" ] || { echo \"[ERR] ROOT not found: \$ROOT\" >&2; exit 1; }")
            add("[ -d \"\$STAGING_DIR\" ] || { echo \"[ERR] STAGING_DIR not found: \$STAGING_DIR\" >&2; exit 1; }")
            add("")
            add("# Prefer deployed WAR paths first, then probe common project-tree/build layouts.")
            add("candidate_target_paths() {")
            add("  local deploy_rel=\"\${1:-}\"")
            add("  local staging_rel=\"\${2:-}\"")
            add("  local class_rel=\"\"")
            add("")
            add("  if [ -z \"\$deploy_rel\" ]; then")
            add("    echo \"[ERR] deploy_rel is empty\" >&2")
            add("    return 1")
            add("  fi")
            add("")
            add("  printf '%s\\n' \"\$ROOT/\$deploy_rel\"")
            add("  if [ -n \"\$staging_rel\" ]; then")
            add("    printf '%s\\n' \"\$ROOT/\$staging_rel\"")
            add("  fi")
            add("")
            add("  case \"\$deploy_rel\" in")
            add("    WEB-INF/jsp/*)")
            add("      printf '%s\\n' \"\$ROOT/src/main/webapp/\$deploy_rel\"")
            add("      ;;")
            add("    WEB-INF/classes/*)")
            add("      class_rel=\"\${deploy_rel#WEB-INF/classes/}\"")
            add("      printf '%s\\n' \"\$ROOT/target/classes/\$class_rel\"")
            add("      printf '%s\\n' \"\$ROOT/build/classes/java/main/\$class_rel\"")
            add("      printf '%s\\n' \"\$ROOT/build/classes/kotlin/main/\$class_rel\"")
            add("      ;;")
            add("  esac")
            add("}")
            add("")
            add("candidate_staging_paths() {")
            add("  local staging_rel=\"\${1:-}\"")
            add("  local deploy_rel=\"\${2:-}\"")
            add("")
            add("  if [ -n \"\$staging_rel\" ]; then")
            add("    printf '%s\\n' \"\$STAGING_DIR/\$staging_rel\"")
            add("  fi")
            add("  if [ -n \"\$deploy_rel\" ]; then")
            add("    printf '%s\\n' \"\$STAGING_DIR/\$deploy_rel\"")
            add("  fi")
            add("}")
            add("")
            add("target_search_suffixes() {")
            add("  local deploy_rel=\"\${1:-}\"")
            add("  local staging_rel=\"\${2:-}\"")
            add("  local class_rel=\"\"")
            add("  local jsp_rel=\"\"")
            add("")
            add("  [ -n \"\$deploy_rel\" ] && printf '%s\\n' \"\$deploy_rel\"")
            add("  [ -n \"\$staging_rel\" ] && printf '%s\\n' \"\$staging_rel\"")
            add("")
            add("  case \"\$deploy_rel\" in")
            add("    WEB-INF/jsp/*)")
            add("      jsp_rel=\"\${deploy_rel#WEB-INF/jsp/}\"")
            add("      printf '%s\\n' \"src/main/webapp/WEB-INF/jsp/\$jsp_rel\"")
            add("      printf '%s\\n' \"\$jsp_rel\"")
            add("      ;;")
            add("    WEB-INF/classes/*)")
            add("      class_rel=\"\${deploy_rel#WEB-INF/classes/}\"")
            add("      printf '%s\\n' \"target/classes/\$class_rel\"")
            add("      printf '%s\\n' \"build/classes/java/main/\$class_rel\"")
            add("      printf '%s\\n' \"build/classes/kotlin/main/\$class_rel\"")
            add("      printf '%s\\n' \"\$class_rel\"")
            add("      ;;")
            add("  esac")
            add("}")
            add("")
            add("find_target_by_suffix() {")
            add("  local deploy_rel=\"\${1:-}\"")
            add("  local staging_rel=\"\${2:-}\"")
            add("  local suffix=\"\"")
            add("  local found=\"\"")
            add("")
            add("  while IFS= read -r suffix; do")
            add("    [ -n \"\$suffix\" ] || continue")
            add("    found=\"\$(find \"\$ROOT\" -type f -path \"*/\$suffix\" -print -quit 2>/dev/null || true)\"")
            add("    if [ -n \"\$found\" ]; then")
            add("      printf '%s\\n' \"\$found\"")
            add("      return 0")
            add("    fi")
            add("  done < <(target_search_suffixes \"\$deploy_rel\" \"\$staging_rel\")")
            add("")
            add("  return 1")
            add("}")
            add("")
            add("find_staging_by_suffix() {")
            add("  local staging_rel=\"\${1:-}\"")
            add("  local deploy_rel=\"\${2:-}\"")
            add("  local suffix=\"\"")
            add("  local found=\"\"")
            add("")
            add("  while IFS= read -r suffix; do")
            add("    [ -n \"\$suffix\" ] || continue")
            add("    found=\"\$(find \"\$STAGING_DIR\" -type f -path \"*/\$suffix\" -print -quit 2>/dev/null || true)\"")
            add("    if [ -n \"\$found\" ]; then")
            add("      printf '%s\\n' \"\$found\"")
            add("      return 0")
            add("    fi")
            add("  done < <(target_search_suffixes \"\$deploy_rel\" \"\$staging_rel\")")
            add("")
            add("  return 1")
            add("}")
            add("")
            add("resolve_staging_path() {")
            add("  local staging_rel=\"\${1:-}\"")
            add("  local deploy_rel=\"\${2:-}\"")
            add("  local first_candidate=\"\"")
            add("  local candidate=\"\"")
            add("  local found=\"\"")
            add("")
            add("  while IFS= read -r candidate; do")
            add("    [ -n \"\$candidate\" ] || continue")
            add("    if [ -z \"\$first_candidate\" ]; then")
            add("      first_candidate=\"\$candidate\"")
            add("    fi")
            add("    if [ -f \"\$candidate\" ]; then")
            add("      printf '%s\\n' \"\$candidate\"")
            add("      return 0")
            add("    fi")
            add("  done < <(candidate_staging_paths \"\$staging_rel\" \"\$deploy_rel\")")
            add("")
            add("  found=\"\$(find_staging_by_suffix \"\$staging_rel\" \"\$deploy_rel\" || true)\"")
            add("  if [ -n \"\$found\" ]; then")
            add("    printf '%s\\n' \"\$found\"")
            add("    return 0")
            add("  fi")
            add("")
            add("  if [ -n \"\$first_candidate\" ]; then")
            add("    printf '%s\\n' \"\$first_candidate\"")
            add("    return 0")
            add("  fi")
            add("")
            add("  echo \"[ERR] Failed to resolve staging path for \$staging_rel\" >&2")
            add("  return 1")
            add("}")
            add("")
            add("resolve_target_path() {")
            add("  local deploy_rel=\"\${1:-}\"")
            add("  local staging_rel=\"\${2:-}\"")
            add("  local first_candidate=\"\"")
            add("  local candidate=\"\"")
            add("  local found=\"\"")
            add("")
            add("  while IFS= read -r candidate; do")
            add("    [ -n \"\$candidate\" ] || continue")
            add("    if [ -z \"\$first_candidate\" ]; then")
            add("      first_candidate=\"\$candidate\"")
            add("    fi")
            add("    if [ -f \"\$candidate\" ]; then")
            add("      printf '%s\\n' \"\$candidate\"")
            add("      return 0")
            add("    fi")
            add("  done < <(candidate_target_paths \"\$deploy_rel\" \"\$staging_rel\")")
            add("")
            add("  found=\"\$(find_target_by_suffix \"\$deploy_rel\" \"\$staging_rel\" || true)\"")
            add("  if [ -n \"\$found\" ]; then")
            add("    printf '%s\\n' \"\$found\"")
            add("    return 0")
            add("  fi")
            add("")
            add("  if [ -n \"\$first_candidate\" ]; then")
            add("    printf '%s\\n' \"\$first_candidate\"")
            add("    return 0")
            add("  fi")
            add("")
            add("  echo \"[ERR] Failed to resolve target path for \$deploy_rel\" >&2")
            add("  return 1")
            add("}")
            add("")
            add("latest_backup_path() {")
            add("  local file=\"\${1:-}\"")
            add("  local dir=\"\"")
            add("  local base=\"\"")
            add("  local latest=\"\"")
            add("")
            add("  [ -n \"\$file\" ] || return 1")
            add("  dir=\"\$(dirname \"\$file\")\"")
            add("  base=\"\$(basename \"\$file\")\"")
            add("  latest=\"\$(find \"\$dir\" -maxdepth 1 -type f -name \"\${base}[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]*\" -print 2>/dev/null | sort | tail -n 1 || true)\"")
            add("  [ -n \"\$latest\" ] || return 1")
            add("  printf '%s\\n' \"\$latest\"")
            add("}")
            add("")
            add("staging_rel_paths=(")
            pathMappings.forEach { (stagingRel, _) -> add("  ${toShellDoubleQuoted(stagingRel)}") }
            add(")")
            add("")
            add("deploy_rel_paths=(")
            pathMappings.forEach { (_, deployRel) -> add("  ${toShellDoubleQuoted(deployRel)}") }
            add(")")
            add("")
            add("resolved_staging_paths=()")
            add("changed_files=()")
            add("for i in \"\${!staging_rel_paths[@]}\"; do")
            add("  rel=\"\${staging_rel_paths[\$i]}\"")
            add("  dst_rel=\"\${deploy_rel_paths[\$i]}\"")
            add("  src=\"\$(resolve_staging_path \"\$rel\" \"\$dst_rel\")\"")
            add("  resolved_staging_paths+=(\"\$src\")")
            add("  if [ -f \"\$src\" ]; then")
            add("    changed_files+=(\"\$src\")")
            add("  else")
            add("    echo \"[WARN] Staging file not found: \$src\" >&2")
            add("  fi")
            add("done")
            add("")
            add("resolved_target_paths=()")
            add("target_states=()")
            add("for i in \"\${!deploy_rel_paths[@]}\"; do")
            add("  rel=\"\${deploy_rel_paths[\$i]}\"")
            add("  src_rel=\"\${staging_rel_paths[\$i]}\"")
            add("  dst=\"\$(resolve_target_path \"\$rel\" \"\$src_rel\")\"")
            add("  resolved_target_paths+=(\"\$dst\")")
            add("  if [ -f \"\$dst\" ]; then")
            add("    target_states+=(\"existing\")")
            add("  else")
            add("    target_states+=(\"new\")")
            add("  fi")
            add("done")
            add("")
            add("while true; do")
            add("  echo")
            add("  echo 'Select mode:'")
            add("  echo '  [b] Backup'")
            add("  echo '  [d] Deploy'")
            add("  echo '  [r] Recover (restore latest backups)'")
            add("  echo '  [c] Cancel'")
            add("  read -p 'Enter choice (b/d/r/c): ' mode")
            add("  case \"\${mode,,}\" in")
            add("    b)")
            add("      echo '[INFO] Pending backup operations:'")
            add("      for i in \"\${!resolved_target_paths[@]}\"; do")
            add("        file=\"\${resolved_target_paths[\$i]}\"")
            add("        state=\"\${target_states[\$i]}\"")
            add("        if [ \"\$state\" = \"existing\" ]; then")
            add("          echo \"  \$(basename \"\$file\") -> \$file\"")
            add("        else")
            add("          echo \"  [new] \$(basename \"\$file\") -> \$file (no backup target)\"")
            add("        fi")
            add("      done")
            add("      echo")
            add("      echo '[INFO] Top-level dirs by extension:'")
            add("      declare -A extDirs=()")
            add("      for file in \"\${resolved_target_paths[@]}\"; do")
            add("        ext=\${file##*.}; dir=\$(dirname \"\$file\")")
            add("        rel=\${dir#\"\$ROOT/\"}")
            add("        prefix=\$(echo \"\$rel\" | awk -F/ '{ for(i=1;i<=NF;i++){ if(\$i==\"WEB-INF\"){ print \$i \"/\" \$(i+1) \"/\" \$(i+2); exit }} }')")
            add("        [ -n \"\$prefix\" ] && extDirs[\"\$ext\"]=\"\$ROOT/\$prefix\" || extDirs[\"\$ext\"]=\"\$dir\"")
            add("      done")
            add("      for e in \"\${!extDirs[@]}\"; do echo \"  .\$e -> \${extDirs[\$e]}\"; done")
            add("      echo")
            add("      read -p 'Proceed with Backup? [y/N]: ' ans")
            add("      case \"\${ans,,}\" in y|yes) ;; *) echo '[CANCEL] Backup canceled.'; exit 1;; esac")
            add("      backup_stamp=\"$backupStampExpr\"")
            add("      echo \"[INFO] Backup start (stamp: \$backup_stamp)\"")
            add("      for i in \"\${!resolved_target_paths[@]}\"; do")
            add("        file=\"\${resolved_target_paths[\$i]}\"")
            add("        state=\"\${target_states[\$i]}\"")
            add("        if [ \"\$state\" != \"existing\" ]; then")
            add("          echo \"  skipped new file: \$file\"")
            add("          continue")
            add("        fi")
            add("        base=\$(basename \"\$file\"); dst_dir=\$(dirname \"\$file\")")
            add("        cp \"\$file\" \"\$dst_dir/\${base}\$backup_stamp\"")
            add("        echo \"  backed up: \$base -> \$dst_dir/\${base}\$backup_stamp\"")
            add("      done")
            add("      echo '[OK] Backup complete.'")
            add("      ;;")
            add("    d)")
            add("      echo '[INFO] Pending deploy operations:'")
            add("      for i in \"\${!deploy_rel_paths[@]}\"; do")
            add("        src_rel=\"\${staging_rel_paths[\$i]}\"")
            add("        dst_rel=\"\${deploy_rel_paths[\$i]}\"")
            add("        src=\"\${resolved_staging_paths[\$i]}\"")
            add("        dst=\"\${resolved_target_paths[\$i]}\"")
            add("        state=\"\${target_states[\$i]}\"")
            add("        name=\$(basename \"\$dst_rel\")")
            add("        if [ ! -f \"\$src\" ]; then echo \"[WARN] Staging file not found: \$src\" >&2; continue; fi")
            add("        if [ \"\$state\" = \"new\" ]; then")
            add("          echo \"  \$name [new]: \$src -> \$dst\"")
            add("        else")
            add("          echo \"  \$name: \$src -> \$dst\"")
            add("        fi")
            add("      done")
            add("      echo")
            add("      echo '[INFO] Top-level dirs by extension:'")
            add("      declare -A extDirs=()")
            add("      for f in \"\${resolved_target_paths[@]}\"; do")
            add("        ext=\${f##*.}; dir=\$(dirname \"\$f\")")
            add("        if [ -z \"\${extDirs[\$ext]+x}\" ]; then extDirs[\"\$ext\"]=\"\$dir\"; fi")
            add("      done")
            add("      for e in \"\${!extDirs[@]}\"; do echo \"  .\$e -> \${extDirs[\$e]}\"; done")
            add("      echo")
            add("      read -p 'Proceed with Deploy? [y/N]: ' ans")
            add("      case \"\${ans,,}\" in y|yes) ;; *) echo '[CANCEL] Deploy canceled.'; exit 1;; esac")
            add("      echo '[INFO] Deploying...'")
            add("      for i in \"\${!deploy_rel_paths[@]}\"; do")
            add("        src_rel=\"\${staging_rel_paths[\$i]}\"")
            add("        dst_rel=\"\${deploy_rel_paths[\$i]}\"")
            add("        src=\"\${resolved_staging_paths[\$i]}\"")
            add("        dst=\"\${resolved_target_paths[\$i]}\"")
            add("        if [ ! -f \"\$src\" ]; then")
            add("          echo \"[WARN] Staging file not found: \$src\" >&2")
            add("          continue")
            add("        fi")
            add("        mkdir -p \"\$(dirname \"\$dst\")\"")
            add("        cp \"\$src\" \"\$dst\"")
            add("        echo \"  deployed: \$(basename \"\$dst_rel\") -> \$dst\"")
            add("      done")
            add("      echo '[OK] Deploy complete.'")
            add("      ;;")
            add("    r)")
            add("      echo '[INFO] Pending recover operations:'")
            add("      for i in \"\${!resolved_target_paths[@]}\"; do")
            add("        file=\"\${resolved_target_paths[\$i]}\"")
            add("        state=\"\${target_states[\$i]}\"")
            add("        if [ \"\$state\" != \"existing\" ]; then")
            add("          echo \"  [skip] \$(basename \"\$file\") -> no original target to recover\"")
            add("          continue")
            add("        fi")
            add("        backup=\"\$(latest_backup_path \"\$file\" || true)\"")
            add("        if [ -z \"\$backup\" ]; then echo \"[WARN] Backup not found: \${file}[0-9]*\" >&2; continue; fi")
            add("        echo \"  \$backup -> \$(basename \"\$file\")\"")
            add("      done")
            add("      echo")
            add("      read -p 'Proceed with Recover? [y/N]: ' ans")
            add("      case \"\${ans,,}\" in y|yes) ;; *) echo '[CANCEL] Recover canceled.'; exit 1;; esac")
            add("      echo '[INFO] Recovering latest backups...'")
            add("      for i in \"\${!resolved_target_paths[@]}\"; do")
            add("        file=\"\${resolved_target_paths[\$i]}\"")
            add("        state=\"\${target_states[\$i]}\"")
            add("        if [ \"\$state\" != \"existing\" ]; then")
            add("          continue")
            add("        fi")
            add("        backup=\"\$(latest_backup_path \"\$file\" || true)\"")
            add("        if [ -f \"\$backup\" ]; then")
            add("          cp \"\$backup\" \"\$file\"")
            add("          echo \"  recovered: \$(basename \"\$file\") <- \$backup\"")
            add("        fi")
            add("      done")
            add("      echo '[OK] Recover complete.'")
            add("      ;;")
            add("    c)")
            add("      echo '[CANCEL] Operation canceled by user, exiting.'")
            add("      break")
            add("      ;;")
            add("    *)")
            add("      echo \"[WARN] Invalid choice: \$mode\" >&2")
            add("      ;;")
            add("  esac")
            add("done")
            add("echo '[DONE] Script finished.'")
        }

        return listOf("patch.sh" to scriptLines)
    }

    private fun normalizeRelativePath(raw: String): String {
        return raw.replace('\\', '/')
            .trimStart('/')
            .replace(Regex("^(?:\\.\\./)+"), "")
    }

    /**
     * Generated shell arrays are wrapped in double quotes, so "$", "\" and "`"
     * must be escaped to keep inner-class names like Foo$1.class literal.
     */
    private fun toShellDoubleQuoted(value: String): String {
        val escaped = value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\$", "\\$")
            .replace("`", "\\`")
        return "\"$escaped\""
    }

    private fun mapToDeployRelativePath(path: String): String {
        return when {
            path.startsWith("src/main/webapp/") -> path.removePrefix("src/main/webapp/")
            path.startsWith("src/main/resources/") -> "WEB-INF/classes/" + path.removePrefix("src/main/resources/")
            Regex("^build/classes/(?:java|kotlin)/main/").containsMatchIn(path) ->
                "WEB-INF/classes/" + path.replaceFirst(Regex("^build/classes/(?:java|kotlin)/main/"), "")
            path.startsWith("build/classes/main/") -> "WEB-INF/classes/" + path.removePrefix("build/classes/main/")
            path.startsWith("target/classes/") -> "WEB-INF/classes/" + path.removePrefix("target/classes/")
            Regex("^out/production/[^/]+/").containsMatchIn(path) ->
                "WEB-INF/classes/" + path.replaceFirst(Regex("^out/production/[^/]+/"), "")
            Regex("^target/[^/]+/WEB-INF/").containsMatchIn(path) -> path.replaceFirst(Regex("^target/[^/]+/"), "")
            Regex("^target/[^/]+/css/").containsMatchIn(path) -> "css/" + path.replaceFirst(Regex("^target/[^/]+/css/"), "")
            Regex("^target/[^/]+/js/").containsMatchIn(path) -> "js/" + path.replaceFirst(Regex("^target/[^/]+/js/"), "")
            else -> path
        }
    }
}
